insert into software (id, software_name) values (1, 'Latlux');
insert into software (id, software_name) values (2, 'Cotlin');
insert into software (id, software_name) values (3, 'Fixflex');
insert into software (id, software_name) values (4, 'Konklux');
insert into software (id, software_name) values (5, 'Span');
insert into software (id, software_name) values (6, 'Redhold');
insert into software (id, software_name) values (7, 'Duobam');
insert into software (id, software_name) values (8, 'Zamit');
insert into software (id, software_name) values (9, 'Mat Lam Tam');
insert into software (id, software_name) values (10, 'Viva');
