insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (1, false, 'Rooxo', 'Service industry', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (2, false, 'Livetube', 'Commerce', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (3, false, 'Edgeclub', 'Unknown', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (4, false, 'Jamia', 'Commerce', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (5, false, 'Kwideo', 'Service industry', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (6, false, 'Pixonyx', 'Production', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (7, false, 'Realblab', 'Unknown', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (8, false, 'LiveZ', 'Production', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (9, false, 'Browsezoom', 'Production', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (10, false, 'Buzzdog', 'Service industry', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (11, false, 'Talane', 'Unknown', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (12, false, 'Jayo', 'Service industry', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (13, false, 'Skiptube', 'Commerce', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (14, false, 'Jaxspan', 'Unknown', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (15, false, 'Feedmix', 'Production', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (16, false, 'Skipfire', 'Commerce', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (17, false, 'Trudeo', 'Unknown', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (18, false, 'Bluejam', 'Unknown', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (19, false, 'EA', 'Production', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (20, false, 'Bubbletube', 'Other', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (21, false, 'Meeveo', 'Other', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (22, false, 'Rhynoodle', 'Production', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (23, false, 'Skaboo', 'Service industry', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (24, false, 'Zoovu', 'Commerce', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (25, false, 'Dabtype', 'Other', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (26, false, 'Jaxworks', 'Production', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (27, false, 'Realpoint', 'Production', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (28, false, 'Oba', 'Other', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (29, false, 'Edgepulse', 'Unknown', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (30, false, 'Valve', 'Other', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (31, false, 'Feedfish', 'Unknown', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (32, false, 'Samsung', 'Service industry', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (33, false, 'Ainyx', 'Production', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (34, false, 'Blognation', 'Service industry', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (35, false, 'Eidel', 'Commerce', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (36, false, 'Voonix', 'Commerce', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (37, false, 'Lazz', 'Service industry', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (38, false, 'Realbuzz', 'Production', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (39, false, 'Midel', 'Commerce', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (40, false, 'Camido', 'Service industry', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (41, false, 'Wordtune', 'Production', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (42, false, 'Zava', 'Production', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (43, false, 'Ozu', 'Commerce', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (44, false, 'Aimbu', 'Commerce', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (45, false, 'Apple', 'Unknown', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (46, false, 'Browsedrive', 'Production', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (47, false, 'Skyba', 'Unknown', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (48, false, 'Brainsphere', 'Production', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (49, false, 'Innotype', 'Production', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (50, false, 'Twinte', 'Production', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (51, false, 'Nlounge', 'Other', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (52, false, 'Dabshots', 'Unknown', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (53, false, 'Thoughtbridge', 'Commerce', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (54, false, 'Leexo', 'Unknown', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (55, false, 'Babbleset', 'Other', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (56, false, 'Jabbertype', 'Commerce', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (57, false, 'Zoombox', 'Other', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (58, false, 'Fivebridge', 'Commerce', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (59, false, 'Tanoodle', 'Unknown', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (60, false, 'Pixope', 'Other', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (61, false, 'Bluezoom', 'Unknown', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (62, false, 'Kwinu', 'Other', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (63, false, 'Tavu', 'Production', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (64, false, 'Twitterbeat', 'Service industry', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (65, false, 'Topicblab', 'Commerce', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (66, false, 'Quimba', 'Other', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (67, false, 'Topicshots', 'Commerce', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (68, false, 'Voomm', 'Other', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (69, false, 'Facebook', 'Commerce', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (70, false, 'Gabtune', 'Commerce', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (71, false, 'Yambee', 'Other', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (72, false, 'Muxo', 'Other', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (73, false, 'Devbug', 'Commerce', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (74, false, 'Vitz', 'Service industry', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (75, false, 'Lajo', 'Service industry', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (76, false, 'Pixoboo', 'Production', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (77, false, 'Livefish', 'Unknown', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (78, false, 'Latz', 'Service industry', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (79, false, 'Meejo', 'Unknown', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (80, false, 'Trilith', 'Service industry', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (81, false, 'Zoonoodle', 'Other', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (82, false, 'Ubisoft', 'Other', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (83, false, 'Meembee', 'Other', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (84, false, 'Google', 'Production', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (85, false, 'Photospace', 'Service industry', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (86, false, 'Flashspan', 'Unknown', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (87, false, 'Eare', 'Unknown', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (88, false, 'Rhyloo', 'Service industry', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (89, false, 'Youtags', 'Commerce', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (90, false, 'Realfire', 'Service industry', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (91, false, 'Vidoo', 'Service industry', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (92, false, 'Ailane', 'Commerce', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (93, false, 'Minyx', 'Other', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (94, false, 'Thoughtstorm', 'Commerce', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (95, false, 'Instagram', 'Unknown', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (96, false, 'Eadel', 'Service industry', 100);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (97, false, 'Dynabox', 'Service industry', 200);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (98, false, 'Devify', 'Production', 300);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (99, false, 'Thoughtsphere', 'Production', 400);
insert into tenant_company (id, isdisabled, title, category, price_per_operator) values (100, false, 'Flipbug', 'Production', 300);
