insert into us_city (id, title, us_state_id) values (1, 'Aberdeen', 6);
insert into us_city (id, title, us_state_id) values (2, 'Abilene', 20);
insert into us_city (id, title, us_state_id) values (3, 'Akron', 24);
insert into us_city (id, title, us_state_id) values (4, 'Albany', 19);
insert into us_city (id, title, us_state_id) values (5, 'Albuquerque', 32);
insert into us_city (id, title, us_state_id) values (6, 'Alexandria', 3);
insert into us_city (id, title, us_state_id) values (7, 'Allentown', 41);
insert into us_city (id, title, us_state_id) values (8, 'Amarillo', 19);
insert into us_city (id, title, us_state_id) values (9, 'Anaheim', 40);
insert into us_city (id, title, us_state_id) values (10, 'Anchorage', 50);
insert into us_city (id, title, us_state_id) values (11, 'Ann Arbor', 19);
insert into us_city (id, title, us_state_id) values (12, 'Antioch', 36);
insert into us_city (id, title, us_state_id) values (13, 'Apple Valley', 42);
insert into us_city (id, title, us_state_id) values (14, 'Appleton', 31);
insert into us_city (id, title, us_state_id) values (15, 'Arlington', 31);
insert into us_city (id, title, us_state_id) values (16, 'Arvada', 35);
insert into us_city (id, title, us_state_id) values (17, 'Asheville', 4);
insert into us_city (id, title, us_state_id) values (18, 'Athens', 17);
insert into us_city (id, title, us_state_id) values (19, 'Atlanta', 24);
insert into us_city (id, title, us_state_id) values (20, 'Atlantic City', 40);
insert into us_city (id, title, us_state_id) values (21, 'Augusta', 16);
insert into us_city (id, title, us_state_id) values (22, 'Aurora', 9);
insert into us_city (id, title, us_state_id) values (23, 'Austin', 28);
insert into us_city (id, title, us_state_id) values (24, 'Bakersfield', 17);
insert into us_city (id, title, us_state_id) values (25, 'Baltimore', 12);
insert into us_city (id, title, us_state_id) values (26, 'Barnstable', 49);
insert into us_city (id, title, us_state_id) values (27, 'Baton Rouge', 28);
insert into us_city (id, title, us_state_id) values (28, 'Beaumont', 13);
insert into us_city (id, title, us_state_id) values (29, 'Bel Air', 37);
insert into us_city (id, title, us_state_id) values (30, 'Bellevue', 12);
insert into us_city (id, title, us_state_id) values (31, 'Berkeley', 18);
insert into us_city (id, title, us_state_id) values (32, 'Bethlehem', 50);
insert into us_city (id, title, us_state_id) values (33, 'Billings', 10);
insert into us_city (id, title, us_state_id) values (34, 'Birmingham', 15);
insert into us_city (id, title, us_state_id) values (35, 'Bloomington', 33);
insert into us_city (id, title, us_state_id) values (36, 'Boise', 36);
insert into us_city (id, title, us_state_id) values (37, 'Boise City', 23);
insert into us_city (id, title, us_state_id) values (38, 'Bonita Springs', 32);
insert into us_city (id, title, us_state_id) values (39, 'Boston', 33);
insert into us_city (id, title, us_state_id) values (40, 'Boulder', 5);
insert into us_city (id, title, us_state_id) values (41, 'Bradenton', 29);
insert into us_city (id, title, us_state_id) values (42, 'Bremerton', 21);
insert into us_city (id, title, us_state_id) values (43, 'Bridgeport', 27);
insert into us_city (id, title, us_state_id) values (44, 'Brighton', 22);
insert into us_city (id, title, us_state_id) values (45, 'Brownsville', 11);
insert into us_city (id, title, us_state_id) values (46, 'Bryan', 39);
insert into us_city (id, title, us_state_id) values (47, 'Buffalo', 45);
insert into us_city (id, title, us_state_id) values (48, 'Burbank', 4);
insert into us_city (id, title, us_state_id) values (49, 'Burlington', 39);
insert into us_city (id, title, us_state_id) values (50, 'Cambridge', 32);
insert into us_city (id, title, us_state_id) values (51, 'Canton', 40);
insert into us_city (id, title, us_state_id) values (52, 'Cape Coral', 34);
insert into us_city (id, title, us_state_id) values (53, 'Carrollton', 5);
insert into us_city (id, title, us_state_id) values (54, 'Cary', 38);
insert into us_city (id, title, us_state_id) values (55, 'Cathedral City', 33);
insert into us_city (id, title, us_state_id) values (56, 'Cedar Rapids', 21);
insert into us_city (id, title, us_state_id) values (57, 'Champaign', 32);
insert into us_city (id, title, us_state_id) values (58, 'Chandler', 5);
insert into us_city (id, title, us_state_id) values (59, 'Charleston', 12);
insert into us_city (id, title, us_state_id) values (60, 'Charlotte', 6);
insert into us_city (id, title, us_state_id) values (61, 'Chattanooga', 50);
insert into us_city (id, title, us_state_id) values (62, 'Chesapeake', 14);
insert into us_city (id, title, us_state_id) values (63, 'Chicago', 22);
insert into us_city (id, title, us_state_id) values (64, 'Chula Vista', 7);
insert into us_city (id, title, us_state_id) values (65, 'Cincinnati', 18);
insert into us_city (id, title, us_state_id) values (66, 'Clarke County', 10);
insert into us_city (id, title, us_state_id) values (67, 'Clarksville', 46);
insert into us_city (id, title, us_state_id) values (68, 'Clearwater', 43);
insert into us_city (id, title, us_state_id) values (69, 'Cleveland', 6);
insert into us_city (id, title, us_state_id) values (70, 'College Station', 7);
insert into us_city (id, title, us_state_id) values (71, 'Colorado Springs', 10);
insert into us_city (id, title, us_state_id) values (72, 'Columbia', 26);
insert into us_city (id, title, us_state_id) values (73, 'Columbus', 5);
insert into us_city (id, title, us_state_id) values (74, 'Concord', 42);
insert into us_city (id, title, us_state_id) values (75, 'Coral Springs', 48);
insert into us_city (id, title, us_state_id) values (76, 'Corona', 42);
insert into us_city (id, title, us_state_id) values (77, 'Corpus Christi', 40);
insert into us_city (id, title, us_state_id) values (78, 'Costa Mesa', 14);
insert into us_city (id, title, us_state_id) values (79, 'Dallas', 41);
insert into us_city (id, title, us_state_id) values (80, 'Daly City', 49);
insert into us_city (id, title, us_state_id) values (81, 'Danbury', 50);
insert into us_city (id, title, us_state_id) values (82, 'Davenport', 15);
insert into us_city (id, title, us_state_id) values (83, 'Davidson County', 49);
insert into us_city (id, title, us_state_id) values (84, 'Dayton', 44);
insert into us_city (id, title, us_state_id) values (85, 'Daytona Beach', 3);
insert into us_city (id, title, us_state_id) values (86, 'Deltona', 12);
insert into us_city (id, title, us_state_id) values (87, 'Denton', 20);
insert into us_city (id, title, us_state_id) values (88, 'Denver', 45);
insert into us_city (id, title, us_state_id) values (89, 'Des Moines', 45);
insert into us_city (id, title, us_state_id) values (90, 'Detroit', 27);
insert into us_city (id, title, us_state_id) values (91, 'Downey', 7);
insert into us_city (id, title, us_state_id) values (92, 'Duluth', 35);
insert into us_city (id, title, us_state_id) values (93, 'Durham', 49);
insert into us_city (id, title, us_state_id) values (94, 'El Monte', 28);
insert into us_city (id, title, us_state_id) values (95, 'El Paso', 17);
insert into us_city (id, title, us_state_id) values (96, 'Elizabeth', 8);
insert into us_city (id, title, us_state_id) values (97, 'Elk Grove', 8);
insert into us_city (id, title, us_state_id) values (98, 'Elkhart', 34);
insert into us_city (id, title, us_state_id) values (99, 'Erie', 11);
insert into us_city (id, title, us_state_id) values (100, 'Escondido', 15);
insert into us_city (id, title, us_state_id) values (101, 'Eugene', 26);
insert into us_city (id, title, us_state_id) values (102, 'Evansville', 34);
insert into us_city (id, title, us_state_id) values (103, 'Fairfield', 50);
insert into us_city (id, title, us_state_id) values (104, 'Fargo', 4);
insert into us_city (id, title, us_state_id) values (105, 'Fayetteville', 25);
insert into us_city (id, title, us_state_id) values (106, 'Fitchburg', 45);
insert into us_city (id, title, us_state_id) values (107, 'Flint', 12);
insert into us_city (id, title, us_state_id) values (108, 'Fontana', 43);
insert into us_city (id, title, us_state_id) values (109, 'Fort Collins', 41);
insert into us_city (id, title, us_state_id) values (110, 'Fort Lauderdale', 18);
insert into us_city (id, title, us_state_id) values (111, 'Fort Smith', 28);
insert into us_city (id, title, us_state_id) values (112, 'Fort Walton Beach', 40);
insert into us_city (id, title, us_state_id) values (113, 'Fort Wayne', 45);
insert into us_city (id, title, us_state_id) values (114, 'Fort Worth', 38);
insert into us_city (id, title, us_state_id) values (115, 'Frederick', 39);
insert into us_city (id, title, us_state_id) values (116, 'Fremont', 19);
insert into us_city (id, title, us_state_id) values (117, 'Fresno', 8);
insert into us_city (id, title, us_state_id) values (118, 'Fullerton', 7);
insert into us_city (id, title, us_state_id) values (119, 'Gainesville', 26);
insert into us_city (id, title, us_state_id) values (120, 'Garden Grove', 12);
insert into us_city (id, title, us_state_id) values (121, 'Garland', 46);
insert into us_city (id, title, us_state_id) values (122, 'Gastonia', 12);
insert into us_city (id, title, us_state_id) values (123, 'Gilbert', 28);
insert into us_city (id, title, us_state_id) values (124, 'Glendale', 28);
insert into us_city (id, title, us_state_id) values (125, 'Grand Prairie', 36);
insert into us_city (id, title, us_state_id) values (126, 'Grand Rapids', 14);
insert into us_city (id, title, us_state_id) values (127, 'Grayslake', 42);
insert into us_city (id, title, us_state_id) values (128, 'Green Bay', 5);
insert into us_city (id, title, us_state_id) values (129, 'GreenBay', 15);
insert into us_city (id, title, us_state_id) values (130, 'Greensboro', 37);
insert into us_city (id, title, us_state_id) values (131, 'Greenville', 38);
insert into us_city (id, title, us_state_id) values (132, 'Gulfport-Biloxi', 44);
insert into us_city (id, title, us_state_id) values (133, 'Hagerstown', 43);
insert into us_city (id, title, us_state_id) values (134, 'Hampton', 7);
insert into us_city (id, title, us_state_id) values (135, 'Harlingen', 48);
insert into us_city (id, title, us_state_id) values (136, 'Harrisburg', 39);
insert into us_city (id, title, us_state_id) values (137, 'Hartford', 16);
insert into us_city (id, title, us_state_id) values (138, 'Havre de Grace', 40);
insert into us_city (id, title, us_state_id) values (139, 'Hayward', 48);
insert into us_city (id, title, us_state_id) values (140, 'Hemet', 14);
insert into us_city (id, title, us_state_id) values (141, 'Henderson', 34);
insert into us_city (id, title, us_state_id) values (142, 'Hesperia', 48);
insert into us_city (id, title, us_state_id) values (143, 'Hialeah', 21);
insert into us_city (id, title, us_state_id) values (144, 'Hickory', 14);
insert into us_city (id, title, us_state_id) values (145, 'High Point', 35);
insert into us_city (id, title, us_state_id) values (146, 'Hollywood', 32);
insert into us_city (id, title, us_state_id) values (147, 'Honolulu', 29);
insert into us_city (id, title, us_state_id) values (148, 'Houma', 17);
insert into us_city (id, title, us_state_id) values (149, 'Houston', 14);
insert into us_city (id, title, us_state_id) values (150, 'Howell', 12);
insert into us_city (id, title, us_state_id) values (151, 'Huntington', 20);
insert into us_city (id, title, us_state_id) values (152, 'Huntington Beach', 6);
insert into us_city (id, title, us_state_id) values (153, 'Huntsville', 44);
insert into us_city (id, title, us_state_id) values (154, 'Independence', 37);
insert into us_city (id, title, us_state_id) values (155, 'Indianapolis', 46);
insert into us_city (id, title, us_state_id) values (156, 'Inglewood', 22);
insert into us_city (id, title, us_state_id) values (157, 'Irvine', 47);
insert into us_city (id, title, us_state_id) values (158, 'Irving', 14);
insert into us_city (id, title, us_state_id) values (159, 'Jackson', 33);
insert into us_city (id, title, us_state_id) values (160, 'Jacksonville', 44);
insert into us_city (id, title, us_state_id) values (161, 'Jefferson', 35);
insert into us_city (id, title, us_state_id) values (162, 'Jersey City', 32);
insert into us_city (id, title, us_state_id) values (163, 'Johnson City', 8);
insert into us_city (id, title, us_state_id) values (164, 'Joliet', 32);
insert into us_city (id, title, us_state_id) values (165, 'Kailua', 45);
insert into us_city (id, title, us_state_id) values (166, 'Kalamazoo', 16);
insert into us_city (id, title, us_state_id) values (167, 'Kaneohe', 12);
insert into us_city (id, title, us_state_id) values (168, 'Kansas City', 8);
insert into us_city (id, title, us_state_id) values (169, 'Kennewick', 43);
insert into us_city (id, title, us_state_id) values (170, 'Kenosha', 23);
insert into us_city (id, title, us_state_id) values (171, 'Killeen', 12);
insert into us_city (id, title, us_state_id) values (172, 'Kissimmee', 33);
insert into us_city (id, title, us_state_id) values (173, 'Knoxville', 12);
insert into us_city (id, title, us_state_id) values (174, 'Lacey', 40);
insert into us_city (id, title, us_state_id) values (175, 'Lafayette', 6);
insert into us_city (id, title, us_state_id) values (176, 'Lake Charles', 4);
insert into us_city (id, title, us_state_id) values (177, 'Lakeland', 41);
insert into us_city (id, title, us_state_id) values (178, 'Lakewood', 14);
insert into us_city (id, title, us_state_id) values (179, 'Lancaster', 5);
insert into us_city (id, title, us_state_id) values (180, 'Lansing', 11);
insert into us_city (id, title, us_state_id) values (181, 'Laredo', 16);
insert into us_city (id, title, us_state_id) values (182, 'Las Cruces', 33);
insert into us_city (id, title, us_state_id) values (183, 'Las Vegas', 43);
insert into us_city (id, title, us_state_id) values (184, 'Layton', 39);
insert into us_city (id, title, us_state_id) values (185, 'Leominster', 14);
insert into us_city (id, title, us_state_id) values (186, 'Lewisville', 44);
insert into us_city (id, title, us_state_id) values (187, 'Lexington', 22);
insert into us_city (id, title, us_state_id) values (188, 'Lincoln', 21);
insert into us_city (id, title, us_state_id) values (189, 'Little Rock', 28);
insert into us_city (id, title, us_state_id) values (190, 'Long Beach', 12);
insert into us_city (id, title, us_state_id) values (191, 'Lorain', 1);
insert into us_city (id, title, us_state_id) values (192, 'Los Angeles', 24);
insert into us_city (id, title, us_state_id) values (193, 'Louisville', 17);
insert into us_city (id, title, us_state_id) values (194, 'Lowell', 12);
insert into us_city (id, title, us_state_id) values (195, 'Lubbock', 28);
insert into us_city (id, title, us_state_id) values (196, 'Macon', 31);
insert into us_city (id, title, us_state_id) values (197, 'Madison', 47);
insert into us_city (id, title, us_state_id) values (198, 'Manchester', 48);
insert into us_city (id, title, us_state_id) values (199, 'Marina', 11);
insert into us_city (id, title, us_state_id) values (200, 'Marysville', 6);
insert into us_city (id, title, us_state_id) values (201, 'McAllen', 30);
insert into us_city (id, title, us_state_id) values (202, 'McHenry', 27);
insert into us_city (id, title, us_state_id) values (203, 'Medford', 7);
insert into us_city (id, title, us_state_id) values (204, 'Melbourne', 21);
insert into us_city (id, title, us_state_id) values (205, 'Memphis', 30);
insert into us_city (id, title, us_state_id) values (206, 'Merced', 46);
insert into us_city (id, title, us_state_id) values (207, 'Mesa', 10);
insert into us_city (id, title, us_state_id) values (208, 'Mesquite', 34);
insert into us_city (id, title, us_state_id) values (209, 'Miami', 45);
insert into us_city (id, title, us_state_id) values (210, 'Milwaukee', 3);
insert into us_city (id, title, us_state_id) values (211, 'Minneapolis', 50);
insert into us_city (id, title, us_state_id) values (212, 'Miramar', 47);
insert into us_city (id, title, us_state_id) values (213, 'Mission Viejo', 7);
insert into us_city (id, title, us_state_id) values (214, 'Mobile', 3);
insert into us_city (id, title, us_state_id) values (215, 'Modesto', 39);
insert into us_city (id, title, us_state_id) values (216, 'Monroe', 17);
insert into us_city (id, title, us_state_id) values (217, 'Monterey', 19);
insert into us_city (id, title, us_state_id) values (218, 'Montgomery', 38);
insert into us_city (id, title, us_state_id) values (219, 'Moreno Valley', 45);
insert into us_city (id, title, us_state_id) values (220, 'Murfreesboro', 16);
insert into us_city (id, title, us_state_id) values (221, 'Murrieta', 47);
insert into us_city (id, title, us_state_id) values (222, 'Muskegon', 31);
insert into us_city (id, title, us_state_id) values (223, 'Myrtle Beach', 28);
insert into us_city (id, title, us_state_id) values (224, 'Naperville', 15);
insert into us_city (id, title, us_state_id) values (225, 'Naples', 35);
insert into us_city (id, title, us_state_id) values (226, 'Nashua', 34);
insert into us_city (id, title, us_state_id) values (227, 'Nashville', 5);
insert into us_city (id, title, us_state_id) values (228, 'New Bedford', 40);
insert into us_city (id, title, us_state_id) values (229, 'New Haven', 22);
insert into us_city (id, title, us_state_id) values (230, 'New London', 9);
insert into us_city (id, title, us_state_id) values (231, 'New Orleans', 41);
insert into us_city (id, title, us_state_id) values (232, 'New York', 47);
insert into us_city (id, title, us_state_id) values (233, 'New York City', 20);
insert into us_city (id, title, us_state_id) values (234, 'Newark', 26);
insert into us_city (id, title, us_state_id) values (235, 'Newburgh', 19);
insert into us_city (id, title, us_state_id) values (236, 'Newport News', 31);
insert into us_city (id, title, us_state_id) values (237, 'Norfolk', 27);
insert into us_city (id, title, us_state_id) values (238, 'Normal', 29);
insert into us_city (id, title, us_state_id) values (239, 'Norman', 39);
insert into us_city (id, title, us_state_id) values (240, 'North Charleston', 29);
insert into us_city (id, title, us_state_id) values (241, 'North Las Vegas', 5);
insert into us_city (id, title, us_state_id) values (242, 'North Port', 2);
insert into us_city (id, title, us_state_id) values (243, 'Norwalk', 47);
insert into us_city (id, title, us_state_id) values (244, 'Norwich', 35);
insert into us_city (id, title, us_state_id) values (245, 'Oakland', 46);
insert into us_city (id, title, us_state_id) values (246, 'Ocala', 48);
insert into us_city (id, title, us_state_id) values (247, 'Oceanside', 48);
insert into us_city (id, title, us_state_id) values (248, 'Odessa', 42);
insert into us_city (id, title, us_state_id) values (249, 'Ogden', 44);
insert into us_city (id, title, us_state_id) values (250, 'Oklahoma City', 33);
insert into us_city (id, title, us_state_id) values (251, 'Olathe', 3);
insert into us_city (id, title, us_state_id) values (252, 'Olympia', 28);
insert into us_city (id, title, us_state_id) values (253, 'Omaha', 35);
insert into us_city (id, title, us_state_id) values (254, 'Ontario', 5);
insert into us_city (id, title, us_state_id) values (255, 'Orange', 44);
insert into us_city (id, title, us_state_id) values (256, 'Orem', 32);
insert into us_city (id, title, us_state_id) values (257, 'Orlando', 3);
insert into us_city (id, title, us_state_id) values (258, 'Overland Park', 21);
insert into us_city (id, title, us_state_id) values (259, 'Oxnard', 15);
insert into us_city (id, title, us_state_id) values (260, 'Palm Bay', 41);
insert into us_city (id, title, us_state_id) values (261, 'Palm Springs', 44);
insert into us_city (id, title, us_state_id) values (262, 'Palmdale', 33);
insert into us_city (id, title, us_state_id) values (263, 'Panama City', 44);
insert into us_city (id, title, us_state_id) values (264, 'Pasadena', 42);
insert into us_city (id, title, us_state_id) values (265, 'Paterson', 11);
insert into us_city (id, title, us_state_id) values (266, 'Pembroke Pines', 19);
insert into us_city (id, title, us_state_id) values (267, 'Pensacola', 43);
insert into us_city (id, title, us_state_id) values (268, 'Peoria', 13);
insert into us_city (id, title, us_state_id) values (269, 'Philadelphia', 32);
insert into us_city (id, title, us_state_id) values (270, 'Phoenix', 30);
insert into us_city (id, title, us_state_id) values (271, 'Pittsburgh', 43);
insert into us_city (id, title, us_state_id) values (272, 'Plano', 25);
insert into us_city (id, title, us_state_id) values (273, 'Pomona', 11);
insert into us_city (id, title, us_state_id) values (274, 'Pompano Beach', 36);
insert into us_city (id, title, us_state_id) values (275, 'Port Arthur', 32);
insert into us_city (id, title, us_state_id) values (276, 'Port Orange', 14);
insert into us_city (id, title, us_state_id) values (277, 'Port Saint Lucie', 28);
insert into us_city (id, title, us_state_id) values (278, 'Port St. Lucie', 22);
insert into us_city (id, title, us_state_id) values (279, 'Portland', 6);
insert into us_city (id, title, us_state_id) values (280, 'Portsmouth', 45);
insert into us_city (id, title, us_state_id) values (281, 'Poughkeepsie', 24);
insert into us_city (id, title, us_state_id) values (282, 'Providence', 48);
insert into us_city (id, title, us_state_id) values (283, 'Provo', 49);
insert into us_city (id, title, us_state_id) values (284, 'Pueblo', 35);
insert into us_city (id, title, us_state_id) values (285, 'Punta Gorda', 48);
insert into us_city (id, title, us_state_id) values (286, 'Racine', 14);
insert into us_city (id, title, us_state_id) values (287, 'Raleigh', 3);
insert into us_city (id, title, us_state_id) values (288, 'Rancho Cucamonga', 20);
insert into us_city (id, title, us_state_id) values (289, 'Reading', 6);
insert into us_city (id, title, us_state_id) values (290, 'Redding', 27);
insert into us_city (id, title, us_state_id) values (291, 'Reno', 41);
insert into us_city (id, title, us_state_id) values (292, 'Richland', 38);
insert into us_city (id, title, us_state_id) values (293, 'Richmond', 28);
insert into us_city (id, title, us_state_id) values (294, 'Richmond County', 28);
insert into us_city (id, title, us_state_id) values (295, 'Riverside', 31);
insert into us_city (id, title, us_state_id) values (296, 'Roanoke', 30);
insert into us_city (id, title, us_state_id) values (297, 'Rochester', 20);
insert into us_city (id, title, us_state_id) values (298, 'Rockford', 32);
insert into us_city (id, title, us_state_id) values (299, 'Roseville', 35);
insert into us_city (id, title, us_state_id) values (300, 'Round Lake Beach', 45);
insert into us_city (id, title, us_state_id) values (301, 'Sacramento', 1);
insert into us_city (id, title, us_state_id) values (302, 'Saginaw', 50);
insert into us_city (id, title, us_state_id) values (303, 'Saint Louis', 44);
insert into us_city (id, title, us_state_id) values (304, 'Saint Paul', 21);
insert into us_city (id, title, us_state_id) values (305, 'Saint Petersburg', 26);
insert into us_city (id, title, us_state_id) values (306, 'Salem', 18);
insert into us_city (id, title, us_state_id) values (307, 'Salinas', 20);
insert into us_city (id, title, us_state_id) values (308, 'Salt Lake City', 34);
insert into us_city (id, title, us_state_id) values (309, 'San Antonio', 11);
insert into us_city (id, title, us_state_id) values (310, 'San Bernardino', 21);
insert into us_city (id, title, us_state_id) values (311, 'San Buenaventura', 50);
insert into us_city (id, title, us_state_id) values (312, 'San Diego', 23);
insert into us_city (id, title, us_state_id) values (313, 'San Francisco', 28);
insert into us_city (id, title, us_state_id) values (314, 'San Jose', 37);
insert into us_city (id, title, us_state_id) values (315, 'Santa Ana', 48);
insert into us_city (id, title, us_state_id) values (316, 'Santa Barbara', 33);
insert into us_city (id, title, us_state_id) values (317, 'Santa Clara', 42);
insert into us_city (id, title, us_state_id) values (318, 'Santa Clarita', 17);
insert into us_city (id, title, us_state_id) values (319, 'Santa Cruz', 12);
insert into us_city (id, title, us_state_id) values (320, 'Santa Maria', 20);
insert into us_city (id, title, us_state_id) values (321, 'Santa Rosa', 24);
insert into us_city (id, title, us_state_id) values (322, 'Sarasota', 44);
insert into us_city (id, title, us_state_id) values (323, 'Savannah', 7);
insert into us_city (id, title, us_state_id) values (324, 'Scottsdale', 40);
insert into us_city (id, title, us_state_id) values (325, 'Scranton', 22);
insert into us_city (id, title, us_state_id) values (326, 'Seaside', 15);
insert into us_city (id, title, us_state_id) values (327, 'Seattle', 1);
insert into us_city (id, title, us_state_id) values (328, 'Sebastian', 38);
insert into us_city (id, title, us_state_id) values (329, 'Shreveport', 43);
insert into us_city (id, title, us_state_id) values (330, 'Simi Valley', 32);
insert into us_city (id, title, us_state_id) values (331, 'Sioux City', 26);
insert into us_city (id, title, us_state_id) values (332, 'Sioux Falls', 20);
insert into us_city (id, title, us_state_id) values (333, 'South Bend', 31);
insert into us_city (id, title, us_state_id) values (334, 'South Lyon', 45);
insert into us_city (id, title, us_state_id) values (335, 'Spartanburg', 22);
insert into us_city (id, title, us_state_id) values (336, 'Spokane', 44);
insert into us_city (id, title, us_state_id) values (337, 'Springdale', 49);
insert into us_city (id, title, us_state_id) values (338, 'Springfield', 42);
insert into us_city (id, title, us_state_id) values (339, 'St. Louis', 27);
insert into us_city (id, title, us_state_id) values (340, 'St. Paul', 38);
insert into us_city (id, title, us_state_id) values (341, 'St. Petersburg', 43);
insert into us_city (id, title, us_state_id) values (342, 'Stamford', 45);
insert into us_city (id, title, us_state_id) values (343, 'Sterling Heights', 44);
insert into us_city (id, title, us_state_id) values (344, 'Stockton', 35);
insert into us_city (id, title, us_state_id) values (345, 'Sunnyvale', 2);
insert into us_city (id, title, us_state_id) values (346, 'Syracuse', 18);
insert into us_city (id, title, us_state_id) values (347, 'Tacoma', 45);
insert into us_city (id, title, us_state_id) values (348, 'Tallahassee', 8);
insert into us_city (id, title, us_state_id) values (349, 'Tampa', 19);
insert into us_city (id, title, us_state_id) values (350, 'Temecula', 24);
insert into us_city (id, title, us_state_id) values (351, 'Tempe', 34);
insert into us_city (id, title, us_state_id) values (352, 'Thornton', 45);
insert into us_city (id, title, us_state_id) values (353, 'Thousand Oaks', 30);
insert into us_city (id, title, us_state_id) values (354, 'Toledo', 9);
insert into us_city (id, title, us_state_id) values (355, 'Topeka', 44);
insert into us_city (id, title, us_state_id) values (356, 'Torrance', 49);
insert into us_city (id, title, us_state_id) values (357, 'Trenton', 45);
insert into us_city (id, title, us_state_id) values (358, 'Tucson', 14);
insert into us_city (id, title, us_state_id) values (359, 'Tulsa', 27);
insert into us_city (id, title, us_state_id) values (360, 'Tuscaloosa', 31);
insert into us_city (id, title, us_state_id) values (361, 'Tyler', 39);
insert into us_city (id, title, us_state_id) values (362, 'Utica', 36);
insert into us_city (id, title, us_state_id) values (363, 'Vallejo', 46);
insert into us_city (id, title, us_state_id) values (364, 'Vancouver', 48);
insert into us_city (id, title, us_state_id) values (365, 'Vero Beach', 12);
insert into us_city (id, title, us_state_id) values (366, 'Victorville', 41);
insert into us_city (id, title, us_state_id) values (367, 'Virginia Beach', 38);
insert into us_city (id, title, us_state_id) values (368, 'Visalia', 17);
insert into us_city (id, title, us_state_id) values (369, 'Waco', 35);
insert into us_city (id, title, us_state_id) values (370, 'Warren', 44);
insert into us_city (id, title, us_state_id) values (371, 'Washington', 42);
insert into us_city (id, title, us_state_id) values (372, 'Waterbury', 9);
insert into us_city (id, title, us_state_id) values (373, 'Waterloo', 19);
insert into us_city (id, title, us_state_id) values (374, 'West Covina', 36);
insert into us_city (id, title, us_state_id) values (375, 'West Valley City', 10);
insert into us_city (id, title, us_state_id) values (376, 'Westminster', 45);
insert into us_city (id, title, us_state_id) values (377, 'Wichita', 40);
insert into us_city (id, title, us_state_id) values (378, 'Wilmington', 31);
insert into us_city (id, title, us_state_id) values (379, 'Winston', 15);
insert into us_city (id, title, us_state_id) values (380, 'Winter Haven', 31);
insert into us_city (id, title, us_state_id) values (381, 'Worcester', 42);
insert into us_city (id, title, us_state_id) values (382, 'Yakima', 8);
insert into us_city (id, title, us_state_id) values (383, 'Yonkers', 25);
insert into us_city (id, title, us_state_id) values (384, 'York', 34);
insert into us_city (id, title, us_state_id) values (385, 'Youngstown', 42);
