# Generated by Django 4.1.3 on 2022-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Operator', 'Operator'), ('TenantCompanyOwner', 'Tenantcompanyowner')], default='Admin', max_length=100),
        ),
    ]
