# Generated by Django 4.1.3 on 2022-12-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center_project', '0005_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='response',
            field=models.CharField(choices=[('Forbidden', 'Forbidden'), ('BusyHere', 'Busyhere'), ('Request_Terminated', 'Requestterminated'), ('OK', 'Ok')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tenantcompany',
            name='category',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Other', 'Other'), ('Production', 'Production'), ('Commerce', 'Commerce'), ('Service_Industry', 'Serviceindustry')], default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Unactive', 'Unactive'), ('Admin', 'Admin'), ('Operator', 'Operator'), ('Tenant_Company_Owner', 'Tenantcompanyowner')], default='Unactive', max_length=100),
        ),
    ]
