# Generated by Django 4.1.5 on 2023-01-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center_project', '0006_alter_calllog_response_alter_tenantcompany_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcompanyphonenumber',
            name='phone_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
