# Generated by Django 4.1.5 on 2023-01-27 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_center_project', '0007_tenantcompanyphonenumber_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcompanyphonenumber',
            name='isdisabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workplace',
            name='operators',
            field=models.ManyToManyField(through='call_center_project.OperatorToWorkPlace', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operatortoworkplace',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operatortoworkplace',
            name='work_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_center_project.workplace'),
        ),
    ]
