# Generated by Django 4.1.7 on 2023-02-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center_project', '0008_tenantcompanyphonenumber_isdisabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Unactive', 'Unactive'), ('Admin', 'Admin'), ('Operator', 'Operator'), ('TenantCompanyOwner', 'Tenantcompanyowner')], default='Unactive', max_length=100),
        ),
    ]
